export const properties = {
  oldKentRoad: {
    cost: 60,
    name: 'Old Kent Road',
    type: 'property',
    color: 'brown',
    blankRent: 2,
    oneHouseRent: 10,
    twoHouseRent: 30,
    threeHouseRent: 90,
    fourHouseRent: 160,
    hotelRent: 250,
    houseCost: 50,
    hotelCost: 50,
    mortgage: 30,
    mortgaged: false,
    houses: 0,
    hotel: false,
    owner: ''
  },
  whitechapelRoad: {
    cost: 60,
    name: 'Whitechapel Road',
    type: 'property',
    color: 'brown',
    blankRent: 4,
    oneHouseRent: 20,
    twoHouseRent: 60,
    threeHouseRent: 180,
    fourHouseRent: 320,
    hotelRent: 450,
    houseCost: 50,
    hotelCost: 50,
    mortgage: 30,
    mortgaged: false,
    houses: 0,
    hotel: false,
    owner: ''
  },
  angelIslington: {
    cost: 100,
    name: 'The Angel Islington',
    type: 'property',
    color: 'Light Blue',
    blankRent: 6,
    oneHouseRent: 30,
    twoHouseRent: 90,
    threeHouseRent: 270,
    fourHouseRent: 400,
    hotelRent: 550,
    houseCost: 50,
    hotelCost: 50,
    mortgage: 50,
    mortgaged: false,
    houses: 0,
    hotel: false,
    owner: ''
  },
  eustonRoad: {
    cost: 100,
    name: 'Euston Road',
    type: 'property',
    color: 'Light Blue',
    blankRent: 6,
    oneHouseRent: 30,
    twoHouseRent: 90,
    threeHouseRent: 270,
    fourHouseRent: 400,
    hotelRent: 550,
    houseCost: 50,
    hotelCost: 50,
    mortgage: 50,
    mortgaged: false,
    houses: 0,
    hotel: false,
    owner: ''
  },
  pentonvilleRoad: {
    cost: 120,
    name: 'Pentonville Road',
    type: 'property',
    color: 'Light Blue',
    blankRent: 8,
    oneHouseRent: 40,
    twoHouseRent: 100,
    threeHouseRent: 300,
    fourHouseRent: 450,
    hotelRent: 600,
    houseCost: 50,
    hotelCost: 50,
    mortgage: 30,
    mortgaged: false,
    houses: 0,
    hotel: false,
    owner: ''
  },
  pallMall: {
    cost: 140,
    name: 'Pall Mall',
    type: 'property',
    color: 'Pink',
    blankRent: 10,
    oneHouseRent: 50,
    twoHouseRent: 150,
    threeHouseRent: 450,
    fourHouseRent: 625,
    hotelRent: 750,
    houseCost: 100,
    hotelCost: 100,
    mortgage: 70,
    mortgaged: false,
    houses: 0,
    hotel: false,
    owner: ''
  },
  whitehall: {
    cost: 140,
    name: 'Whitehall',
    type: 'property',
    color: 'Pink',
    blankRent: 10,
    oneHouseRent: 50,
    twoHouseRent: 150,
    threeHouseRent: 450,
    fourHouseRent: 625,
    hotelRent: 750,
    houseCost: 100,
    hotelCost: 100,
    mortgage: 70,
    mortgaged: false,
    houses: 0,
    hotel: false,
    owner: ''
  },
  northumberlandAvenue: {
    cost: 160,
    name: 'Northumberland Avenue',
    type: 'property',
    color: 'Pink',
    blankRent: 12,
    oneHouseRent: 60,
    twoHouseRent: 180,
    threeHouseRent: 500,
    fourHouseRent: 700,
    hotelRent: 900,
    houseCost: 100,
    hotelCost: 100,
    mortgage: 80,
    mortgaged: false,
    houses: 0,
    hotel: false,
    owner: ''
  },
  bowStreet: {
    cost: 180,
    name: 'Bow Street',
    type: 'property',
    color: 'Orange',
    blankRent: 14,
    oneHouseRent: 70,
    twoHouseRent: 200,
    threeHouseRent: 550,
    fourHouseRent: 750,
    hotelRent: 950,
    houseCost: 100,
    hotelCost: 100,
    mortgage: 90,
    mortgaged: false,
    houses: 0,
    hotel: false,
    owner: ''
  },
  marlboroughStreet: {
    cost: 180,
    name: 'Marlborough Street',
    type: 'property',
    color: 'Orange',
    blankRent: 14,
    oneHouseRent: 70,
    twoHouseRent: 200,
    threeHouseRent: 550,
    fourHouseRent: 750,
    hotelRent: 950,
    houseCost: 100,
    hotelCost: 100,
    mortgage: 90,
    mortgaged: false,
    houses: 0,
    hotel: false,
    owner: ''
  },
  vineStreet: {
    cost: 200,
    name: 'Vine Street',
    type: 'property',
    color: 'Orange',
    blankRent: 16,
    oneHouseRent: 80,
    twoHouseRent: 220,
    threeHouseRent: 600,
    fourHouseRent: 800,
    hotelRent: 1000,
    houseCost: 100,
    hotelCost: 100,
    mortgage: 100,
    mortgaged: false,
    houses: 0,
    hotel: false,
    owner: ''
  },
  strand: {
    cost: 220,
    name: 'Strand',
    type: 'property',
    color: 'Red',
    blankRent: 18,
    oneHouseRent: 90,
    twoHouseRent: 250,
    threeHouseRent: 700,
    fourHouseRent: 875,
    hotelRent: 1050,
    houseCost: 150,
    hotelCost: 150,
    mortgage: 110,
    mortgaged: false,
    houses: 0,
    hotel: false,
    owner: ''
  },
  fleetStreet: {
    cost: 220,
    name: 'Fleet Street',
    type: 'property',
    color: 'Red',
    blankRent: 18,
    oneHouseRent: 90,
    twoHouseRent: 250,
    threeHouseRent: 700,
    fourHouseRent: 875,
    hotelRent: 1050,
    houseCost: 150,
    hotelCost: 150,
    mortgage: 110,
    mortgaged: false,
    houses: 0,
    hotel: false,
    owner: ''
  },
  trafalgarSquare: {
    cost: 240,
    name: 'Trafalgar Square',
    type: 'property',
    color: 'Orange',
    blankRent: 20,
    oneHouseRent: 100,
    twoHouseRent: 300,
    threeHouseRent: 750,
    fourHouseRent: 925,
    hotelRent: 1100,
    houseCost: 150,
    hotelCost: 150,
    mortgage: 120,
    mortgaged: false,
    houses: 0,
    hotel: false,
    owner: ''
  },
  leicesterSquare: {
    cost: 260,
    name: 'Leicester Square',
    type: 'property',
    color: 'Yellow',
    blankRent: 22,
    oneHouseRent: 110,
    twoHouseRent: 330,
    threeHouseRent: 800,
    fourHouseRent: 975,
    hotelRent: 1150,
    houseCost: 150,
    hotelCost: 150,
    mortgage: 130,
    mortgaged: false,
    houses: 0,
    hotel: false,
    owner: ''
  },
  coventryStreet: {
    cost: 260,
    name: 'Coventry Street',
    type: 'property',
    color: 'Yellow',
    blankRent: 22,
    oneHouseRent: 110,
    twoHouseRent: 330,
    threeHouseRent: 800,
    fourHouseRent: 975,
    hotelRent: 1150,
    houseCost: 150,
    hotelCost: 150,
    mortgage: 130,
    mortgaged: false,
    houses: 0,
    hotel: false,
    owner: ''
  },
  piccadilly: {
    cost: 280,
    name: 'Piccadilly',
    type: 'property',
    color: 'Yellow',
    blankRent: 24,
    oneHouseRent: 120,
    twoHouseRent: 360,
    threeHouseRent: 850,
    fourHouseRent: 1025,
    hotelRent: 1200,
    houseCost: 150,
    hotelCost: 150,
    mortgage: 140,
    mortgaged: false,
    houses: 0,
    hotel: false,
    owner: ''
  },
  regentStreet: {
    cost: 300,
    name: 'Regent Street',
    type: 'property',
    color: 'Green',
    blankRent: 26,
    oneHouseRent: 130,
    twoHouseRent: 390,
    threeHouseRent: 900,
    fourHouseRent: 1100,
    hotelRent: 1275,
    houseCost: 200,
    hotelCost: 200,
    mortgage: 150,
    mortgaged: false,
    houses: 0,
    hotel: false,
    owner: ''
  },
  oxfordStreet: {
    cost: 300,
    name: 'Oxford Street',
    type: 'property',
    color: 'Green',
    blankRent: 26,
    oneHouseRent: 130,
    twoHouseRent: 390,
    threeHouseRent: 900,
    fourHouseRent: 1100,
    hotelRent: 1275,
    houseCost: 200,
    hotelCost: 200,
    mortgage: 150,
    mortgaged: false,
    houses: 0,
    hotel: false,
    owner: ''
  },
  bondStreet: {
    cost: 320,
    name: 'Bond Street',
    type: 'property',
    color: 'Green',
    blankRent: 28,
    oneHouseRent: 150,
    twoHouseRent: 450,
    threeHouseRent: 1100,
    fourHouseRent: 1200,
    hotelRent: 1400,
    houseCost: 200,
    hotelCost: 200,
    mortgage: 160,
    mortgaged: false,
    houses: 0,
    hotel: false,
    owner: ''
  },
  parkLane: {
    cost: 350,
    name: 'Park Lane',
    type: 'property',
    color: 'Dark Blue',
    blankRent: 35,
    oneHouseRent: 175,
    twoHouseRent: 500,
    threeHouseRent: 1100,
    fourHouseRent: 1300,
    hotelRent: 1500,
    houseCost: 200,
    hotelCost: 200,
    mortgage: 175,
    mortgaged: false,
    houses: 0,
    hotel: false,
    owner: ''
  },
  mayfair: {
    cost: 400,
    name: 'Mayfair',
    type: 'property',
    color: 'Dark Blue',
    blankRent: 50,
    oneHouseRent: 200,
    twoHouseRent: 600,
    threeHouseRent: 1400,
    fourHouseRent: 1700,
    hotelRent: 2000,
    houseCost: 200,
    hotelCost: 200,
    mortgage: 200,
    mortgaged: false,
    houses: 0,
    hotel: false,
    owner: ''
  }
}

export const stations = {
  liverpoolStreetStation: {
    cost: 200,
    name: 'Liverpool Street Station',
    rent: 25,
    twoOwnedRent: 50,
    threeOwnedRent: 100,
    fourOwnedRent: 200,
    mortgage: 100,
    mortgaged: false,
    owner: ''
  },
  fenchurchStreetStation: {
    cost: 200,
    name: 'Fenchurch St Station',
    rent: 25,
    twoOwnedRent: 50,
    threeOwnedRent: 100,
    fourOwnedRent: 200,
    mortgage: 100,
    mortgaged: false,
    owner: ''
  },
  kingsCrossStation: {
    cost: 200,
    name: 'Kings Cross Station',
    rent: 25,
    twoOwnedRent: 50,
    threeOwnedRent: 100,
    fourOwnedRent: 200,
    mortgage: 100,
    mortgaged: false,
    owner: ''
  },
  maryleboneStation: {
    cost: 200,
    name: 'Marylebone Station',
    rent: 25,
    twoOwnedRent: 50,
    threeOwnedRent: 100,
    fourOwnedRent: 200,
    mortgage: 100,
    mortgaged: false,
    owner: ''
  }
}

export const utilities = {
  electric: {
    name: 'Electric Company',
    cost: 150,
    singleRentMultiplier: 4,
    doubleRentMultiplier: 10,
    mortgage: 75,
    mortgaged: false,
    owner: ''
  },
  water: {
    name: 'Water Works',
    cost: 150,
    singleRentMultiplier: 4,
    doubleRentMultiplier: 10,
    mortgage: 75,
    mortgaged: false,
    owner: ''
  }
}

export const taxes = {
  incomeTax: {
    name: 'Income Tax',
    cost: 200
  },
  superTax: {
    name: 'Super Tax',
    cost: 100
  }
}

export const corners = {
  go: {
    name: 'GO',
    gain: 200,
    cost: 0
  },
  parking: {
    name: 'Free Parking',
    gain: 0,
    cost: 0
  },
  jail: {
    name: 'Jail',
    gain: 0,
    cost: 0
  },
  goToJail: {
    name: 'Go To jail',
    gain: 0,
    cost: 0
  }
}

export const cellOrder = [
  { name: 'go', type: 'corner' },
  { name: 'oldKentRoad', type: 'property' },
  { name: 'comunityChest', type: 'card' },
  { name: 'whitechapelRoad', type: 'property' },
  { name: 'incomeTax', type: 'tax' },
  { name: 'kingsCrossStation', type: 'station' },
  { name: 'angelIslington', type: 'property' },
  { name: 'chance', type: 'card' },
  { name: 'eustonRoad', type: 'property' },
  { name: 'pentonvilleRoad', type: 'property' },
  { name: 'jail', type: 'corner' },
  { name: 'pallMall', type: 'property' },
  { name: 'electric', type: 'utility' },
  { name: 'whitehall', type: 'property' },
  { name: 'northumberlandAvenue', type: 'property' },
  { name: 'maryleboneStation', type: 'station' },
  { name: 'bowStreet', type: 'property' },
  { name: 'comunityChest', type: 'card' },
  { name: 'marlboroughStreet', type: 'property' },
  { name: 'vineStreet', type: 'property' },
  { name: 'parking', type: 'corner' },
  { name: 'strand', type: 'property' },
  { name: 'chance', type: 'card' },
  { name: 'fleetStreet', type: 'property' },
  { name: 'trafalgarSquare', type: 'property' },
  { name: 'fenchurchStreetStation', type: 'station' },
  { name: 'leicesterSquare', type: 'property' },
  { name: 'coventryStreet', type: 'property' },
  { name: 'water', type: 'utility' },
  { name: 'piccadilly', type: 'property' },
  { name: 'goToJail', type: 'corner' },
  { name: 'regentStreet', type: 'property' },
  { name: 'oxfordStreet', type: 'property' },
  { name: 'comunityChest', type: 'card' },
  { name: 'bondStreet', type: 'property' },
  { name: 'liverpoolStreetStation', type: 'station' },
  { name: 'chance', type: 'card' },
  { name: 'parkLane', type: 'property' },
  { name: 'superTax', type: 'tax' },
  { name: 'mayfair', type: 'property' }
]